###
POST http://localhost:5163/register
Content-Type: application/json

{
  "name": "McQueen",
  "password": "12345"
}

### 
POST http://localhost:5163/message
Content-Type: application/json

{
  "content": "This a test message",
  "from": "McQueen"
}

###
POST http://localhost:5163/login
Content-Type: application/json

{
  "name": "McQueen",
  "password": "12345"
}
