# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x1b\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\tUserReply\x12\x13\n\x0buser_exists\x18\x01 \x01(\x08\"\x1e\n\x0b\x43reateReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32R\n\x04User\x12\"\n\x04\x46ind\x12\x0c.UserRequest\x1a\n.UserReply\"\x00\x12&\n\x06\x43reate\x12\x0c.UserRequest\x1a\x0c.CreateReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=14
  _globals['_USERREQUEST']._serialized_end=41
  _globals['_USERREPLY']._serialized_start=43
  _globals['_USERREPLY']._serialized_end=75
  _globals['_CREATEREPLY']._serialized_start=77
  _globals['_CREATEREPLY']._serialized_end=107
  _globals['_USER']._serialized_start=109
  _globals['_USER']._serialized_end=191
# @@protoc_insertion_point(module_scope)
